# Generated by Django 3.0.6 on 2020-05-27 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200527_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 5, 27, 18, 58, 32, 215880), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 5, 27, 18, 58, 32, 216880), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='answer',
            field=models.CharField(max_length=3, verbose_name='Получить ответ?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('1', 'Ошибка'), ('2', 'Блог'), ('3', 'Авторские права')], max_length=1, verbose_name='Категория вопроса'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 5, 27, 18, 58, 32, 213879), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Электронная почта'),
        ),
    ]
