# Generated by Django 3.0.6 on 2020-05-28 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200528_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 5, 28, 12, 5, 11, 209021), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 5, 28, 12, 5, 11, 211021), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='answer',
            field=models.BooleanField(default=False, verbose_name='Получить ответ?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 5, 28, 12, 5, 11, 206021), verbose_name='Дата'),
        ),
    ]
