# Generated by Django 3.0.6 on 2020-05-28 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200528_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 5, 28, 12, 9, 44, 478651), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 5, 28, 12, 9, 44, 479651), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 5, 28, 12, 9, 44, 476651), verbose_name='Дата'),
        ),
    ]
